# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'TransitionsInput.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDoubleSpinBox, QFrame,
    QLabel, QLineEdit, QPlainTextEdit, QScrollArea,
    QSizePolicy, QSpinBox, QTimeEdit, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(411, 957)
        self.vaiable_input_string = QScrollArea(Form)
        self.vaiable_input_string.setObjectName(u"vaiable_input_string")
        self.vaiable_input_string.setGeometry(QRect(0, 0, 411, 951))
        self.vaiable_input_string.setFrameShadow(QFrame.Sunken)
        self.vaiable_input_string.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.vaiable_input_string.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.vaiable_input_string.setWidgetResizable(True)
        self.scrollAreaWidgetContents_7 = QWidget()
        self.scrollAreaWidgetContents_7.setObjectName(u"scrollAreaWidgetContents_7")
        self.scrollAreaWidgetContents_7.setGeometry(QRect(0, 0, 409, 949))
        self.variable_input = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input.setObjectName(u"variable_input")
        self.variable_input.setGeometry(QRect(10, 40, 401, 27))
        self.initial_value_label = QLabel(self.variable_input)
        self.initial_value_label.setObjectName(u"initial_value_label")
        self.initial_value_label.setGeometry(QRect(0, 0, 111, 21))
        font = QFont()
        font.setPointSize(12)
        self.initial_value_label.setFont(font)
        self.initial_value_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.activity_name_input = QLineEdit(self.variable_input)
        self.activity_name_input.setObjectName(u"activity_name_input")
        self.activity_name_input.setGeometry(QRect(160, 0, 231, 25))
        self.header_label = QLabel(self.scrollAreaWidgetContents_7)
        self.header_label.setObjectName(u"header_label")
        self.header_label.setGeometry(QRect(10, 5, 391, 21))
        self.header_label.setFont(font)
        self.header_label.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.line_17 = QFrame(self.scrollAreaWidgetContents_7)
        self.line_17.setObjectName(u"line_17")
        self.line_17.setGeometry(QRect(0, 30, 411, 3))
        self.line_17.setFrameShadow(QFrame.Plain)
        self.line_17.setFrameShape(QFrame.HLine)
        self.variable_input_4 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_4.setObjectName(u"variable_input_4")
        self.variable_input_4.setGeometry(QRect(10, 70, 401, 27))
        self.initial_value_label_3 = QLabel(self.variable_input_4)
        self.initial_value_label_3.setObjectName(u"initial_value_label_3")
        self.initial_value_label_3.setGeometry(QRect(0, 0, 121, 21))
        self.initial_value_label_3.setFont(font)
        self.initial_value_label_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.weight_input = QDoubleSpinBox(self.variable_input_4)
        self.weight_input.setObjectName(u"weight_input")
        self.weight_input.setGeometry(QRect(160, 0, 231, 25))
        self.weight_input.setMaximum(1000.000000000000000)
        self.weight_input.setValue(1.000000000000000)
        self.variable_input_7 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_7.setObjectName(u"variable_input_7")
        self.variable_input_7.setGeometry(QRect(10, 186, 401, 21))
        self.initial_value_label_6 = QLabel(self.variable_input_7)
        self.initial_value_label_6.setObjectName(u"initial_value_label_6")
        self.initial_value_label_6.setGeometry(QRect(0, 0, 231, 21))
        self.initial_value_label_6.setFont(font)
        self.initial_value_label_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.no_time_forwarding_input = QCheckBox(self.variable_input_7)
        self.no_time_forwarding_input.setObjectName(u"no_time_forwarding_input")
        self.no_time_forwarding_input.setGeometry(QRect(210, 0, 82, 23))
        self.variable_input_8 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_8.setObjectName(u"variable_input_8")
        self.variable_input_8.setGeometry(QRect(10, 140, 401, 31))
        self.initial_value_label_5 = QLabel(self.variable_input_8)
        self.initial_value_label_5.setObjectName(u"initial_value_label_5")
        self.initial_value_label_5.setGeometry(QRect(0, 10, 231, 21))
        self.initial_value_label_5.setFont(font)
        self.initial_value_label_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.general_config_input = QCheckBox(self.variable_input_8)
        self.general_config_input.setObjectName(u"general_config_input")
        self.general_config_input.setGeometry(QRect(210, 10, 82, 23))
        self.time_delay_maximum = QWidget(self.scrollAreaWidgetContents_7)
        self.time_delay_maximum.setObjectName(u"time_delay_maximum")
        self.time_delay_maximum.setGeometry(QRect(10, 340, 391, 25))
        self.output_dir_label_19 = QLabel(self.time_delay_maximum)
        self.output_dir_label_19.setObjectName(u"output_dir_label_19")
        self.output_dir_label_19.setGeometry(QRect(20, 0, 191, 21))
        self.output_dir_label_19.setFont(font)
        self.output_dir_label_19.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.time_delay_maximum_time_input = QTimeEdit(self.time_delay_maximum)
        self.time_delay_maximum_time_input.setObjectName(u"time_delay_maximum_time_input")
        self.time_delay_maximum_time_input.setGeometry(QRect(300, 0, 81, 25))
        font1 = QFont()
        font1.setPointSize(11)
        self.time_delay_maximum_time_input.setFont(font1)
        self.time_delay_maximum_time_input.setMinimumTime(QTime(0, 0, 1))
        self.time_delay_maximum_time_input.setTime(QTime(0, 0, 1))
        self.time_delay_maximum_days_input = QSpinBox(self.time_delay_maximum)
        self.time_delay_maximum_days_input.setObjectName(u"time_delay_maximum_days_input")
        self.time_delay_maximum_days_input.setGeometry(QRect(230, 0, 51, 25))
        self.time_delay_maximum_days_input.setFont(font1)
        self.time_delay_maximum_days_input.setMinimum(0)
        self.time_delay_maximum_days_input.setMaximum(10000)
        self.time_delay_maximum_days_input.setValue(0)
        self.output_dir_label_22 = QLabel(self.scrollAreaWidgetContents_7)
        self.output_dir_label_22.setObjectName(u"output_dir_label_22")
        self.output_dir_label_22.setGeometry(QRect(300, 220, 101, 23))
        self.output_dir_label_22.setFont(font1)
        self.output_dir_label_22.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.avg_trans_delay = QWidget(self.scrollAreaWidgetContents_7)
        self.avg_trans_delay.setObjectName(u"avg_trans_delay")
        self.avg_trans_delay.setGeometry(QRect(10, 247, 391, 25))
        self.output_dir_label_16 = QLabel(self.avg_trans_delay)
        self.output_dir_label_16.setObjectName(u"output_dir_label_16")
        self.output_dir_label_16.setGeometry(QRect(0, 0, 191, 21))
        self.output_dir_label_16.setFont(font)
        self.output_dir_label_16.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.avg_trans_delay_time_input = QTimeEdit(self.avg_trans_delay)
        self.avg_trans_delay_time_input.setObjectName(u"avg_trans_delay_time_input")
        self.avg_trans_delay_time_input.setGeometry(QRect(300, 0, 81, 25))
        self.avg_trans_delay_time_input.setFont(font1)
        self.avg_trans_delay_time_input.setMinimumTime(QTime(0, 0, 0))
        self.avg_trans_delay_time_input.setTime(QTime(0, 0, 0))
        self.avg_trans_delay_days_input = QSpinBox(self.avg_trans_delay)
        self.avg_trans_delay_days_input.setObjectName(u"avg_trans_delay_days_input")
        self.avg_trans_delay_days_input.setGeometry(QRect(230, 0, 51, 25))
        self.avg_trans_delay_days_input.setFont(font1)
        self.avg_trans_delay_days_input.setMinimum(0)
        self.avg_trans_delay_days_input.setMaximum(10000)
        self.avg_trans_delay_days_input.setValue(0)
        self.output_dir_label_17 = QLabel(self.scrollAreaWidgetContents_7)
        self.output_dir_label_17.setObjectName(u"output_dir_label_17")
        self.output_dir_label_17.setGeometry(QRect(245, 220, 41, 23))
        self.output_dir_label_17.setFont(font1)
        self.output_dir_label_17.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.time_delay_minimum = QWidget(self.scrollAreaWidgetContents_7)
        self.time_delay_minimum.setObjectName(u"time_delay_minimum")
        self.time_delay_minimum.setGeometry(QRect(10, 309, 391, 25))
        self.output_dir_label_20 = QLabel(self.time_delay_minimum)
        self.output_dir_label_20.setObjectName(u"output_dir_label_20")
        self.output_dir_label_20.setGeometry(QRect(20, 0, 191, 21))
        self.output_dir_label_20.setFont(font)
        self.output_dir_label_20.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.time_delay_minimum_days_input = QSpinBox(self.time_delay_minimum)
        self.time_delay_minimum_days_input.setObjectName(u"time_delay_minimum_days_input")
        self.time_delay_minimum_days_input.setGeometry(QRect(230, 0, 51, 25))
        self.time_delay_minimum_days_input.setFont(font1)
        self.time_delay_minimum_days_input.setMinimum(0)
        self.time_delay_minimum_days_input.setMaximum(10000)
        self.time_delay_minimum_days_input.setValue(0)
        self.time_delay_minimum_time_input = QTimeEdit(self.time_delay_minimum)
        self.time_delay_minimum_time_input.setObjectName(u"time_delay_minimum_time_input")
        self.time_delay_minimum_time_input.setGeometry(QRect(300, 0, 81, 25))
        self.time_delay_minimum_time_input.setFont(font1)
        self.time_delay_sd = QWidget(self.scrollAreaWidgetContents_7)
        self.time_delay_sd.setObjectName(u"time_delay_sd")
        self.time_delay_sd.setGeometry(QRect(10, 278, 391, 25))
        self.output_dir_label_18 = QLabel(self.time_delay_sd)
        self.output_dir_label_18.setObjectName(u"output_dir_label_18")
        self.output_dir_label_18.setGeometry(QRect(20, 0, 201, 21))
        self.output_dir_label_18.setFont(font)
        self.output_dir_label_18.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.time_delay_sd_days_input = QSpinBox(self.time_delay_sd)
        self.time_delay_sd_days_input.setObjectName(u"time_delay_sd_days_input")
        self.time_delay_sd_days_input.setGeometry(QRect(230, 0, 51, 25))
        self.time_delay_sd_days_input.setFont(font1)
        self.time_delay_sd_days_input.setMinimum(0)
        self.time_delay_sd_days_input.setMaximum(10000)
        self.time_delay_sd_days_input.setValue(0)
        self.time_delay_sd_time_input = QTimeEdit(self.time_delay_sd)
        self.time_delay_sd_time_input.setObjectName(u"time_delay_sd_time_input")
        self.time_delay_sd_time_input.setGeometry(QRect(300, 0, 81, 25))
        self.time_delay_sd_time_input.setFont(font1)
        self.time_delay_sd_time_input.setMinimumTime(QTime(0, 0, 1))
        self.time_delay_sd_time_input.setTime(QTime(0, 0, 1))
        self.time_delay_sd_2 = QWidget(self.scrollAreaWidgetContents_7)
        self.time_delay_sd_2.setObjectName(u"time_delay_sd_2")
        self.time_delay_sd_2.setGeometry(QRect(10, 419, 391, 25))
        self.output_dir_label_27 = QLabel(self.time_delay_sd_2)
        self.output_dir_label_27.setObjectName(u"output_dir_label_27")
        self.output_dir_label_27.setGeometry(QRect(20, 0, 141, 21))
        self.output_dir_label_27.setFont(font)
        self.output_dir_label_27.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.time_lead_sd_days_input = QSpinBox(self.time_delay_sd_2)
        self.time_lead_sd_days_input.setObjectName(u"time_lead_sd_days_input")
        self.time_lead_sd_days_input.setGeometry(QRect(230, 0, 51, 25))
        self.time_lead_sd_days_input.setFont(font1)
        self.time_lead_sd_days_input.setMinimum(0)
        self.time_lead_sd_days_input.setMaximum(10000)
        self.time_lead_sd_days_input.setValue(0)
        self.time_lead_sd_time_input = QTimeEdit(self.time_delay_sd_2)
        self.time_lead_sd_time_input.setObjectName(u"time_lead_sd_time_input")
        self.time_lead_sd_time_input.setGeometry(QRect(300, 0, 81, 25))
        self.time_lead_sd_time_input.setFont(font1)
        self.time_lead_sd_time_input.setMinimumTime(QTime(0, 0, 1))
        self.time_lead_sd_time_input.setTime(QTime(0, 0, 1))
        self.time_delay_maximum_2 = QWidget(self.scrollAreaWidgetContents_7)
        self.time_delay_maximum_2.setObjectName(u"time_delay_maximum_2")
        self.time_delay_maximum_2.setGeometry(QRect(10, 481, 391, 25))
        self.output_dir_label_28 = QLabel(self.time_delay_maximum_2)
        self.output_dir_label_28.setObjectName(u"output_dir_label_28")
        self.output_dir_label_28.setGeometry(QRect(20, 0, 191, 21))
        self.output_dir_label_28.setFont(font)
        self.output_dir_label_28.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.time_lead_maximum_time_input = QTimeEdit(self.time_delay_maximum_2)
        self.time_lead_maximum_time_input.setObjectName(u"time_lead_maximum_time_input")
        self.time_lead_maximum_time_input.setGeometry(QRect(300, 0, 81, 25))
        self.time_lead_maximum_time_input.setFont(font1)
        self.time_lead_maximum_time_input.setMinimumTime(QTime(0, 0, 1))
        self.time_lead_maximum_time_input.setTime(QTime(0, 0, 1))
        self.time_lead_maximum_days_input = QSpinBox(self.time_delay_maximum_2)
        self.time_lead_maximum_days_input.setObjectName(u"time_lead_maximum_days_input")
        self.time_lead_maximum_days_input.setGeometry(QRect(230, 0, 51, 25))
        self.time_lead_maximum_days_input.setFont(font1)
        self.time_lead_maximum_days_input.setMinimum(0)
        self.time_lead_maximum_days_input.setMaximum(10000)
        self.time_lead_maximum_days_input.setValue(0)
        self.time_delay_minimum_2 = QWidget(self.scrollAreaWidgetContents_7)
        self.time_delay_minimum_2.setObjectName(u"time_delay_minimum_2")
        self.time_delay_minimum_2.setGeometry(QRect(10, 450, 391, 25))
        self.output_dir_label_29 = QLabel(self.time_delay_minimum_2)
        self.output_dir_label_29.setObjectName(u"output_dir_label_29")
        self.output_dir_label_29.setGeometry(QRect(20, 0, 191, 21))
        self.output_dir_label_29.setFont(font)
        self.output_dir_label_29.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.time_lead_minimum_days_input = QSpinBox(self.time_delay_minimum_2)
        self.time_lead_minimum_days_input.setObjectName(u"time_lead_minimum_days_input")
        self.time_lead_minimum_days_input.setGeometry(QRect(230, 0, 51, 25))
        self.time_lead_minimum_days_input.setFont(font1)
        self.time_lead_minimum_days_input.setMinimum(0)
        self.time_lead_minimum_days_input.setMaximum(10000)
        self.time_lead_minimum_days_input.setValue(0)
        self.time_lead_minimum_time_input = QTimeEdit(self.time_delay_minimum_2)
        self.time_lead_minimum_time_input.setObjectName(u"time_lead_minimum_time_input")
        self.time_lead_minimum_time_input.setGeometry(QRect(300, 0, 81, 25))
        self.time_lead_minimum_time_input.setFont(font1)
        self.avg_trans_delay_2 = QWidget(self.scrollAreaWidgetContents_7)
        self.avg_trans_delay_2.setObjectName(u"avg_trans_delay_2")
        self.avg_trans_delay_2.setGeometry(QRect(10, 388, 391, 25))
        self.output_dir_label_30 = QLabel(self.avg_trans_delay_2)
        self.output_dir_label_30.setObjectName(u"output_dir_label_30")
        self.output_dir_label_30.setGeometry(QRect(0, 0, 191, 21))
        self.output_dir_label_30.setFont(font)
        self.output_dir_label_30.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.avg_trans_lead_time_input = QTimeEdit(self.avg_trans_delay_2)
        self.avg_trans_lead_time_input.setObjectName(u"avg_trans_lead_time_input")
        self.avg_trans_lead_time_input.setGeometry(QRect(300, 0, 81, 25))
        self.avg_trans_lead_time_input.setFont(font1)
        self.avg_trans_lead_time_input.setMinimumTime(QTime(0, 0, 0))
        self.avg_trans_lead_time_input.setTime(QTime(0, 0, 0))
        self.avg_trans_lead_days_input = QSpinBox(self.avg_trans_delay_2)
        self.avg_trans_lead_days_input.setObjectName(u"avg_trans_lead_days_input")
        self.avg_trans_lead_days_input.setGeometry(QRect(230, 0, 51, 25))
        self.avg_trans_lead_days_input.setFont(font1)
        self.avg_trans_lead_days_input.setMinimum(0)
        self.avg_trans_lead_days_input.setMaximum(10000)
        self.avg_trans_lead_days_input.setValue(0)
        self.initial_value_label_4 = QLabel(self.scrollAreaWidgetContents_7)
        self.initial_value_label_4.setObjectName(u"initial_value_label_4")
        self.initial_value_label_4.setGeometry(QRect(10, 110, 201, 21))
        self.initial_value_label_4.setFont(font)
        self.initial_value_label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.invisible_input = QCheckBox(self.scrollAreaWidgetContents_7)
        self.invisible_input.setObjectName(u"invisible_input")
        self.invisible_input.setGeometry(QRect(220, 110, 181, 23))
        self.scrollArea = QScrollArea(self.scrollAreaWidgetContents_7)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(10, 794, 391, 141))
        self.scrollArea.setWidgetResizable(True)
        self.scroll_area_contents = QWidget()
        self.scroll_area_contents.setObjectName(u"scroll_area_contents")
        self.scroll_area_contents.setGeometry(QRect(0, 0, 389, 139))
        self.scrollArea.setWidget(self.scroll_area_contents)
        self.output_dir_label_31 = QLabel(self.scrollAreaWidgetContents_7)
        self.output_dir_label_31.setObjectName(u"output_dir_label_31")
        self.output_dir_label_31.setGeometry(QRect(10, 770, 381, 21))
        self.output_dir_label_31.setFont(font)
        self.output_dir_label_31.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.time_intervals_input = QPlainTextEdit(self.scrollAreaWidgetContents_7)
        self.time_intervals_input.setObjectName(u"time_intervals_input")
        self.time_intervals_input.setGeometry(QRect(10, 550, 391, 141))
        self.output_dir_label_32 = QLabel(self.scrollAreaWidgetContents_7)
        self.output_dir_label_32.setObjectName(u"output_dir_label_32")
        self.output_dir_label_32.setGeometry(QRect(10, 520, 381, 21))
        self.output_dir_label_32.setFont(font)
        self.output_dir_label_32.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.variance_input = QCheckBox(self.scrollAreaWidgetContents_7)
        self.variance_input.setObjectName(u"variance_input")
        self.variance_input.setGeometry(QRect(240, 710, 161, 23))
        self.initial_value_label_7 = QLabel(self.scrollAreaWidgetContents_7)
        self.initial_value_label_7.setObjectName(u"initial_value_label_7")
        self.initial_value_label_7.setGeometry(QRect(10, 710, 221, 21))
        self.initial_value_label_7.setFont(font)
        self.initial_value_label_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.initial_value_label_8 = QLabel(self.scrollAreaWidgetContents_7)
        self.initial_value_label_8.setObjectName(u"initial_value_label_8")
        self.initial_value_label_8.setGeometry(QRect(10, 740, 221, 21))
        self.initial_value_label_8.setFont(font)
        self.initial_value_label_8.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.max_variance_input = QSpinBox(self.scrollAreaWidgetContents_7)
        self.max_variance_input.setObjectName(u"max_variance_input")
        self.max_variance_input.setGeometry(QRect(240, 740, 161, 25))
        self.max_variance_input.setMaximum(10000)
        self.vaiable_input_string.setWidget(self.scrollAreaWidgetContents_7)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
#if QT_CONFIG(tooltip)
        self.variable_input.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>The name that will be displayed in the event created in the event log if this transition is fired.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label.setText(QCoreApplication.translate("Form", u"Activity Name:", None))
#if QT_CONFIG(tooltip)
        self.header_label.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>The Id and the name of the transition.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.header_label.setText(QCoreApplication.translate("Form", u"ID", None))
#if QT_CONFIG(tooltip)
        self.variable_input_4.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This setting influences the random choice of a transition if multiple transitions are enabled. This value can be any positive real number. For example, if transition A has a weight of 5 and transition B has a weight of 1, transition A is 5 times more likely to be chosen.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_4.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_3.setText(QCoreApplication.translate("Form", u"Weight:", None))
#if QT_CONFIG(tooltip)
        self.variable_input_7.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>If this setting is checked the transition will have no delay and no lead time.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_7.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_6.setText(QCoreApplication.translate("Form", u"No Time Forwarding:", None))
        self.no_time_forwarding_input.setText("")
#if QT_CONFIG(tooltip)
        self.variable_input_8.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>If this setting is checked the general settings displayed in the top of the &quot;Transition Configuration&quot; area will be used instead of the individual settings below.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_8.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_5.setText(QCoreApplication.translate("Form", u"Use General Configuration:", None))
        self.general_config_input.setText("")
#if QT_CONFIG(tooltip)
        self.time_delay_maximum.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>These settings influence the amount of time that passes before this transition is fired after the previous transition finished.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.output_dir_label_19.setText(QCoreApplication.translate("Form", u"Maximum:", None))
        self.time_delay_maximum_time_input.setDisplayFormat(QCoreApplication.translate("Form", u"HH:mm:ss", None))
        self.output_dir_label_22.setText(QCoreApplication.translate("Form", u"Hours:Min:Sec", None))
#if QT_CONFIG(tooltip)
        self.avg_trans_delay.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>These settings influence the amount of time that passes before this transition is fired after the previous transition finished.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.output_dir_label_16.setText(QCoreApplication.translate("Form", u"Avg. Time Delay:", None))
        self.avg_trans_delay_time_input.setDisplayFormat(QCoreApplication.translate("Form", u"HH:mm:ss", None))
        self.output_dir_label_17.setText(QCoreApplication.translate("Form", u"Days", None))
#if QT_CONFIG(tooltip)
        self.time_delay_minimum.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>These settings influence the amount of time that passes before this transition is fired after the previous transition finished.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.output_dir_label_20.setText(QCoreApplication.translate("Form", u"Minimum:", None))
        self.time_delay_minimum_time_input.setDisplayFormat(QCoreApplication.translate("Form", u"HH:mm:ss", None))
#if QT_CONFIG(tooltip)
        self.time_delay_sd.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>These settings influence the amount of time that passes before this transition is fired after the previous transition finished.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.output_dir_label_18.setText(QCoreApplication.translate("Form", u"Standard Deviation:", None))
        self.time_delay_sd_time_input.setDisplayFormat(QCoreApplication.translate("Form", u"HH:mm:ss", None))
#if QT_CONFIG(tooltip)
        self.time_delay_sd_2.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>These settings influence the amount of time that is needed for the completion of the transition.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.output_dir_label_27.setText(QCoreApplication.translate("Form", u"Standard Deviation:", None))
        self.time_lead_sd_time_input.setDisplayFormat(QCoreApplication.translate("Form", u"HH:mm:ss", None))
#if QT_CONFIG(tooltip)
        self.time_delay_maximum_2.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>These settings influence the amount of time that is needed for the completion of the transition.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.output_dir_label_28.setText(QCoreApplication.translate("Form", u"Maximum:", None))
        self.time_lead_maximum_time_input.setDisplayFormat(QCoreApplication.translate("Form", u"HH:mm:ss", None))
#if QT_CONFIG(tooltip)
        self.time_delay_minimum_2.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>These settings influence the amount of time that is needed for the completion of the transition.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.output_dir_label_29.setText(QCoreApplication.translate("Form", u"Minimum:", None))
        self.time_lead_minimum_time_input.setDisplayFormat(QCoreApplication.translate("Form", u"HH:mm:ss", None))
#if QT_CONFIG(tooltip)
        self.avg_trans_delay_2.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>These settings influence the amount of time that is needed for the completion of the transition.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.output_dir_label_30.setText(QCoreApplication.translate("Form", u"Avg. Lead Time:", None))
        self.avg_trans_lead_time_input.setDisplayFormat(QCoreApplication.translate("Form", u"HH:mm:ss", None))
#if QT_CONFIG(tooltip)
        self.initial_value_label_4.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This setting allows to set a transition to be invisible. Invisible transitions are do not appear in the event log but do influence the control flow of the model.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.initial_value_label_4.setText(QCoreApplication.translate("Form", u"Invisible:", None))
#if QT_CONFIG(tooltip)
        self.invisible_input.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This setting allows to set a transition to be invisible. Invisible transitions are do not appear in the event log but do influence the control flow of the model.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.invisible_input.setText("")
#if QT_CONFIG(tooltip)
        self.scrollArea.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This area allows you to define which variables are included in the event that is created if this transition is fired. A variable is included in the event if it has a value, is not a trace variable, and the checkbox next to the variable is checked.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.output_dir_label_31.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This area allows you to define which variables are included in the event that is created if this transition is fired. A variable is included in the event if it has a value, is not a trace variable, and the checkbox next to the variable is checked.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.output_dir_label_31.setText(QCoreApplication.translate("Form", u"Included Variables", None))
#if QT_CONFIG(tooltip)
        self.time_intervals_input.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This input allows you to restrict when the activity can be performed. Therefore, a list of time intervals can be provided. If not Intervals are provided, no restrictions aply. The following syntax has to be used:</p><p align=\"center\">Mon,Tue,Wed,Thu,Fri,Sat,Sun | 07:00:00-12:00:00;</p><p align=\"center\">Mon,Tue,Wed,Thu,Fri | 14:00:00-18:00:00;</p><p align=\"center\">.....</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.output_dir_label_32.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This input allows you to restrict when the activity can be performed. Therefore, a list of time intervals can be provided. If not Intervals are provided, no restrictions aply. The following syntax has to be used:</p><p align=\"center\">Mon,Tue,Wed,Thu,Fri,Sat,Sun | 07:00:00-12:00:00;</p><p align=\"center\">Mon,Tue,Wed,Thu,Fri | 14:00:00-18:00:00;</p><p align=\"center\">.....</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.output_dir_label_32.setText(QCoreApplication.translate("Form", u"Time Intervals", None))
#if QT_CONFIG(tooltip)
        self.variance_input.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This input allows you to add variance to the timestamp of an activity if the activity is at the beginning of a time interval. If this setting is not usesd all timestamps that are originally outside of the time intervals will be at the beginning of the next valid interval. </p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.variance_input.setText("")
#if QT_CONFIG(tooltip)
        self.initial_value_label_7.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This input allows you to add variance to the timestamp of an activity if the activity is at the beginning of a time interval. If this setting is not usesd all timestamps that are originally outside of the time intervals will be at the beginning of the next valid interval. </p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.initial_value_label_7.setText(QCoreApplication.translate("Form", u"Add Time Interval Variance:", None))
#if QT_CONFIG(tooltip)
        self.initial_value_label_8.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This input allows you set the maximum variance.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.initial_value_label_8.setText(QCoreApplication.translate("Form", u"Maximum Variance (Minutes):", None))
#if QT_CONFIG(tooltip)
        self.max_variance_input.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This input allows you set the maximum variance.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
    # retranslateUi

