# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'VariableInputInt.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QFrame, QLabel, QPlainTextEdit, QScrollArea,
    QSizePolicy, QSpinBox, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(411, 861)
        self.vaiable_input_string = QScrollArea(Form)
        self.vaiable_input_string.setObjectName(u"vaiable_input_string")
        self.vaiable_input_string.setGeometry(QRect(0, 0, 411, 861))
        self.vaiable_input_string.setFrameShadow(QFrame.Sunken)
        self.vaiable_input_string.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.vaiable_input_string.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.vaiable_input_string.setWidgetResizable(True)
        self.scrollAreaWidgetContents_7 = QWidget()
        self.scrollAreaWidgetContents_7.setObjectName(u"scrollAreaWidgetContents_7")
        self.scrollAreaWidgetContents_7.setGeometry(QRect(0, 0, 409, 859))
        self.variable_input = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input.setObjectName(u"variable_input")
        self.variable_input.setGeometry(QRect(10, 120, 401, 27))
        self.initial_value_label = QLabel(self.variable_input)
        self.initial_value_label.setObjectName(u"initial_value_label")
        self.initial_value_label.setGeometry(QRect(0, 0, 91, 21))
        font = QFont()
        font.setPointSize(12)
        self.initial_value_label.setFont(font)
        self.initial_value_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.initial_value_input = QSpinBox(self.variable_input)
        self.initial_value_input.setObjectName(u"initial_value_input")
        self.initial_value_input.setGeometry(QRect(160, 0, 231, 25))
        self.initial_value_input.setMinimum(-99999999)
        self.initial_value_input.setMaximum(99999999)
        self.header_label = QLabel(self.scrollAreaWidgetContents_7)
        self.header_label.setObjectName(u"header_label")
        self.header_label.setGeometry(QRect(10, 5, 391, 21))
        self.header_label.setFont(font)
        self.header_label.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.line_17 = QFrame(self.scrollAreaWidgetContents_7)
        self.line_17.setObjectName(u"line_17")
        self.line_17.setGeometry(QRect(0, 30, 411, 3))
        self.line_17.setFrameShadow(QFrame.Plain)
        self.line_17.setFrameShape(QFrame.HLine)
        self.variable_input_2 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_2.setObjectName(u"variable_input_2")
        self.variable_input_2.setGeometry(QRect(10, 480, 401, 81))
        self.initial_value_label_2 = QLabel(self.variable_input_2)
        self.initial_value_label_2.setObjectName(u"initial_value_label_2")
        self.initial_value_label_2.setGeometry(QRect(0, 0, 51, 21))
        self.initial_value_label_2.setFont(font)
        self.initial_value_label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.values_input = QPlainTextEdit(self.variable_input_2)
        self.values_input.setObjectName(u"values_input")
        self.values_input.setGeometry(QRect(110, 5, 281, 71))
        self.values_input.setFont(font)
        self.variable_input_3 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_3.setObjectName(u"variable_input_3")
        self.variable_input_3.setGeometry(QRect(10, 560, 401, 81))
        self.dependencies_label = QLabel(self.variable_input_3)
        self.dependencies_label.setObjectName(u"dependencies_label")
        self.dependencies_label.setGeometry(QRect(0, 0, 111, 21))
        self.dependencies_label.setFont(font)
        self.dependencies_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.dependencies_input = QPlainTextEdit(self.variable_input_3)
        self.dependencies_input.setObjectName(u"dependencies_input")
        self.dependencies_input.setGeometry(QRect(110, 5, 281, 71))
        self.dependencies_input.setFont(font)
        self.variable_input_4 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_4.setObjectName(u"variable_input_4")
        self.variable_input_4.setGeometry(QRect(10, 230, 401, 27))
        self.initial_value_label_3 = QLabel(self.variable_input_4)
        self.initial_value_label_3.setObjectName(u"initial_value_label_3")
        self.initial_value_label_3.setGeometry(QRect(0, 0, 121, 21))
        self.initial_value_label_3.setFont(font)
        self.initial_value_label_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.minimum_value_input = QSpinBox(self.variable_input_4)
        self.minimum_value_input.setObjectName(u"minimum_value_input")
        self.minimum_value_input.setGeometry(QRect(160, 0, 231, 25))
        self.minimum_value_input.setMinimum(-99999999)
        self.minimum_value_input.setMaximum(99999999)
        self.variable_input_5 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_5.setObjectName(u"variable_input_5")
        self.variable_input_5.setGeometry(QRect(10, 260, 401, 27))
        self.initial_value_label_4 = QLabel(self.variable_input_5)
        self.initial_value_label_4.setObjectName(u"initial_value_label_4")
        self.initial_value_label_4.setGeometry(QRect(0, 0, 121, 21))
        self.initial_value_label_4.setFont(font)
        self.initial_value_label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.maximum_value_input = QSpinBox(self.variable_input_5)
        self.maximum_value_input.setObjectName(u"maximum_value_input")
        self.maximum_value_input.setGeometry(QRect(160, 0, 231, 25))
        self.maximum_value_input.setMinimum(-99999999)
        self.maximum_value_input.setMaximum(99999999)
        self.maximum_value_input.setValue(100)
        self.variable_input_6 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_6.setObjectName(u"variable_input_6")
        self.variable_input_6.setGeometry(QRect(10, 710, 401, 81))
        self.dependencies_label_2 = QLabel(self.variable_input_6)
        self.dependencies_label_2.setObjectName(u"dependencies_label_2")
        self.dependencies_label_2.setGeometry(QRect(0, 0, 111, 21))
        self.dependencies_label_2.setFont(font)
        self.dependencies_label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.intervals_input = QPlainTextEdit(self.variable_input_6)
        self.intervals_input.setObjectName(u"intervals_input")
        self.intervals_input.setGeometry(QRect(110, 5, 281, 71))
        self.variable_input_7 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_7.setObjectName(u"variable_input_7")
        self.variable_input_7.setGeometry(QRect(10, 360, 401, 27))
        self.initial_value_label_5 = QLabel(self.variable_input_7)
        self.initial_value_label_5.setObjectName(u"initial_value_label_5")
        self.initial_value_label_5.setGeometry(QRect(0, 0, 101, 21))
        self.initial_value_label_5.setFont(font)
        self.initial_value_label_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.distribution_input = QComboBox(self.variable_input_7)
        self.distribution_input.setObjectName(u"distribution_input")
        self.distribution_input.setGeometry(QRect(110, 0, 281, 25))
        self.variable_input_8 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_8.setObjectName(u"variable_input_8")
        self.variable_input_8.setGeometry(QRect(10, 300, 401, 51))
        self.used_info_input = QComboBox(self.variable_input_8)
        self.used_info_input.setObjectName(u"used_info_input")
        self.used_info_input.setGeometry(QRect(160, 0, 231, 25))
        self.used_info_input.setEditable(False)
        self.initial_value_label_8 = QLabel(self.variable_input_8)
        self.initial_value_label_8.setObjectName(u"initial_value_label_8")
        self.initial_value_label_8.setGeometry(QRect(0, 0, 181, 51))
        self.initial_value_label_8.setFont(font)
        self.initial_value_label_8.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.variable_input_9 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_9.setObjectName(u"variable_input_9")
        self.variable_input_9.setGeometry(QRect(10, 400, 401, 27))
        self.initial_value_label_9 = QLabel(self.variable_input_9)
        self.initial_value_label_9.setObjectName(u"initial_value_label_9")
        self.initial_value_label_9.setGeometry(QRect(0, 0, 141, 21))
        self.initial_value_label_9.setFont(font)
        self.initial_value_label_9.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.distribution_mean_input = QDoubleSpinBox(self.variable_input_9)
        self.distribution_mean_input.setObjectName(u"distribution_mean_input")
        self.distribution_mean_input.setGeometry(QRect(180, 0, 211, 25))
        self.distribution_mean_input.setDecimals(4)
        self.distribution_mean_input.setMinimum(-99999999.000000000000000)
        self.distribution_mean_input.setMaximum(99999999.000000000000000)
        self.variable_input_10 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_10.setObjectName(u"variable_input_10")
        self.variable_input_10.setGeometry(QRect(10, 430, 401, 51))
        self.initial_value_label_10 = QLabel(self.variable_input_10)
        self.initial_value_label_10.setObjectName(u"initial_value_label_10")
        self.initial_value_label_10.setGeometry(QRect(0, 0, 151, 51))
        self.initial_value_label_10.setFont(font)
        self.initial_value_label_10.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.distribution_sd_input = QDoubleSpinBox(self.variable_input_10)
        self.distribution_sd_input.setObjectName(u"distribution_sd_input")
        self.distribution_sd_input.setGeometry(QRect(180, 20, 211, 25))
        self.distribution_sd_input.setDecimals(4)
        self.distribution_sd_input.setMinimum(0.000000000000000)
        self.distribution_sd_input.setMaximum(99999999.000000000000000)
        self.distribution_sd_input.setValue(1.000000000000000)
        self.variable_input_11 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_11.setObjectName(u"variable_input_11")
        self.variable_input_11.setGeometry(QRect(10, 50, 401, 27))
        self.initial_value_label_6 = QLabel(self.variable_input_11)
        self.initial_value_label_6.setObjectName(u"initial_value_label_6")
        self.initial_value_label_6.setGeometry(QRect(0, 0, 121, 21))
        self.initial_value_label_6.setFont(font)
        self.initial_value_label_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.use_initial_value_input = QCheckBox(self.variable_input_11)
        self.use_initial_value_input.setObjectName(u"use_initial_value_input")
        self.use_initial_value_input.setGeometry(QRect(140, 0, 82, 23))
        self.variable_input_12 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_12.setObjectName(u"variable_input_12")
        self.variable_input_12.setGeometry(QRect(10, 800, 401, 27))
        self.initial_value_label_7 = QLabel(self.variable_input_12)
        self.initial_value_label_7.setObjectName(u"initial_value_label_7")
        self.initial_value_label_7.setGeometry(QRect(0, 0, 181, 21))
        self.initial_value_label_7.setFont(font)
        self.initial_value_label_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.inverse_intervals_input = QCheckBox(self.variable_input_12)
        self.inverse_intervals_input.setObjectName(u"inverse_intervals_input")
        self.inverse_intervals_input.setGeometry(QRect(200, 0, 82, 23))
        self.gen_initial_value = QWidget(self.scrollAreaWidgetContents_7)
        self.gen_initial_value.setObjectName(u"gen_initial_value")
        self.gen_initial_value.setGeometry(QRect(10, 80, 401, 27))
        self.initial_value_label_11 = QLabel(self.gen_initial_value)
        self.initial_value_label_11.setObjectName(u"initial_value_label_11")
        self.initial_value_label_11.setGeometry(QRect(0, 0, 161, 21))
        self.initial_value_label_11.setFont(font)
        self.initial_value_label_11.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.gen_initial_value_input = QCheckBox(self.gen_initial_value)
        self.gen_initial_value_input.setObjectName(u"gen_initial_value_input")
        self.gen_initial_value_input.setGeometry(QRect(160, 0, 82, 23))
        self.fixed_variable = QWidget(self.scrollAreaWidgetContents_7)
        self.fixed_variable.setObjectName(u"fixed_variable")
        self.fixed_variable.setGeometry(QRect(10, 160, 401, 27))
        self.initial_value_label_12 = QLabel(self.fixed_variable)
        self.initial_value_label_12.setObjectName(u"initial_value_label_12")
        self.initial_value_label_12.setGeometry(QRect(0, 0, 121, 21))
        self.initial_value_label_12.setFont(font)
        self.initial_value_label_12.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.fixed_variable_input = QCheckBox(self.fixed_variable)
        self.fixed_variable_input.setObjectName(u"fixed_variable_input")
        self.fixed_variable_input.setGeometry(QRect(140, 0, 82, 23))
        self.trace_variable = QWidget(self.scrollAreaWidgetContents_7)
        self.trace_variable.setObjectName(u"trace_variable")
        self.trace_variable.setGeometry(QRect(10, 190, 401, 27))
        self.initial_value_label_13 = QLabel(self.trace_variable)
        self.initial_value_label_13.setObjectName(u"initial_value_label_13")
        self.initial_value_label_13.setGeometry(QRect(0, 0, 131, 21))
        self.initial_value_label_13.setFont(font)
        self.initial_value_label_13.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.trace_variable_input = QCheckBox(self.trace_variable)
        self.trace_variable_input.setObjectName(u"trace_variable_input")
        self.trace_variable_input.setGeometry(QRect(140, 0, 82, 23))
        self.self_deviation = QWidget(self.scrollAreaWidgetContents_7)
        self.self_deviation.setObjectName(u"self_deviation")
        self.self_deviation.setGeometry(QRect(10, 650, 401, 51))
        self.initial_value_label_15 = QLabel(self.self_deviation)
        self.initial_value_label_15.setObjectName(u"initial_value_label_15")
        self.initial_value_label_15.setGeometry(QRect(0, 0, 191, 51))
        self.initial_value_label_15.setFont(font)
        self.initial_value_label_15.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.self_deviation_input = QSpinBox(self.self_deviation)
        self.self_deviation_input.setObjectName(u"self_deviation_input")
        self.self_deviation_input.setGeometry(QRect(210, 15, 91, 25))
        font1 = QFont()
        font1.setPointSize(11)
        self.self_deviation_input.setFont(font1)
        self.self_deviation_input.setMaximum(99999999)
        self.vaiable_input_string.setWidget(self.scrollAreaWidgetContents_7)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
#if QT_CONFIG(tooltip)
        self.variable_input.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>If the above option is checked this setting let's you adjust the initial value.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label.setText(QCoreApplication.translate("Form", u"Initial Value:", None))
#if QT_CONFIG(tooltip)
        self.header_label.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>The name and the type of the variable.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.header_label.setText(QCoreApplication.translate("Form", u"NAME (TYPE)", None))
#if QT_CONFIG(tooltip)
        self.variable_input_2.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This field allows to specify valid values for the variable. These values are used if a transition writes to the variable. The specification has to be done using the following syntax:</p><p align=\"center\">&quot;value1&quot;, &quot;value2&quot;, ...</p><p>Optionally weights can be specified for each value. Each weight has to be a whole positive number. If weights are specified they have to be specified using the following syntax:</p><p align=\"center\">&quot;value1&quot;, &quot;value2&quot; | value1_weight, value2_weight</p><p>If weights are specified the number of specified values must equal the number of specified weights.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_2.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_2.setText(QCoreApplication.translate("Form", u"Values:", None))
#if QT_CONFIG(tooltip)
        self.variable_input_3.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This field allows to specify dependencies of the variable. These dependencies are considered when generating values for this variable. The specification has to be done using the following syntax:</p><p align=\"center\">&quot;logical_expression&quot; =&gt; &quot;constraint1&quot;, dependency2, ...</p><p>Example for the variable &quot;cancer_type&quot;: </p><p align=\"center\">&quot;gender == 'female' &quot; =&gt; &quot; '!=' ; 'prostate cancer' &quot;</p><p>The logical expression has to follow the same syntax as the guard transitions in a PNML model. The constraints have to follow the following syntax:</p><p align=\"center\">&quot; 'operator' ; 'value' &quot;</p><p>The operators that are alowed are: &quot;&lt;&quot;, &quot;&lt;=&quot;, &quot;&gt;&quot;, &quot;&gt;=&quot;, &quot;==&quot;, &quot;!=&quot; For date variables the value has to be input in the following syntax: &quot;yyyy-MM-ddThh:mm:ss&quot;</p><p><br/></p><p>In addition to &quot;normal&quot; dependencies this input field can al"
                        "so be used to use the &quot;self_reference&quot; feature, which is only available for numeric and date variables. This feature allows you to have variable values change every time they are written to while reference to them self. The following syntax must be used for this feature.</p><p align=\"center\">&quot;SELF_REFERENCE&quot; =&gt; &quot; '+' ; '5' &quot;</p><p>In the above example the variable value will be increased by 5 every time the variable is written to. However, it should be noted that this dependency only gets activated when the variable alredy has a value. The allowed operators for this feature are &quot;+&quot;, &quot;-&quot;, &quot;/&quot;, and &quot;*&quot;. For Date variables the value has to be input in the following syntax: &quot;dd:hh:mm:ss&quot;. </p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_3.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.dependencies_label.setText(QCoreApplication.translate("Form", u"Dependencies:", None))
#if QT_CONFIG(tooltip)
        self.variable_input_4.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This setting let's you set a minimum value for all values generated for this variable.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_4.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_3.setText(QCoreApplication.translate("Form", u"Minimum Value:", None))
#if QT_CONFIG(tooltip)
        self.variable_input_5.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This setting let's you set a maximum value for all values generated for this variable.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_5.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_4.setText(QCoreApplication.translate("Form", u"Maximum Value:", None))
#if QT_CONFIG(tooltip)
        self.variable_input_6.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This setting allows to specify intervals for the value generation for this variable. If intervals are used a random interval will be chosen and a value will be generated that lies inside this interval. The following syntax must be used to specify intervals:</p><p align=\"center\">(&quot;operator&quot; ; &quot;boundry&quot;), (&quot;operator&quot; ; &quot;boundry&quot;)...</p><p align=\"center\">Allowed operators: &quot;&lt;&quot;, &quot;&gt;&quot;, &quot;&lt;=&quot;, &quot;&gt;=&quot;</p><p align=\"center\">example: (&quot;&lt;&quot; ; &quot;1.0&quot;)</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_6.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.dependencies_label_2.setText(QCoreApplication.translate("Form", u"Intervals:", None))
#if QT_CONFIG(tooltip)
        self.variable_input_7.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This setting allows to change the type of the distribution used to generate values for this variable.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_7.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_5.setText(QCoreApplication.translate("Form", u"Distribution:", None))
#if QT_CONFIG(tooltip)
        self.variable_input_8.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This setting allows to specify which information is used to generate the values for this variable.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_8.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_8.setText(QCoreApplication.translate("Form", u"Information used for\n"
"value generation:", None))
#if QT_CONFIG(tooltip)
        self.variable_input_9.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>The mean value that the distribution should have.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_9.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_9.setText(QCoreApplication.translate("Form", u"Distribution Mean:", None))
#if QT_CONFIG(tooltip)
        self.variable_input_10.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>The standard deviation that the distribution should have.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_10.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_10.setText(QCoreApplication.translate("Form", u"Distribution\n"
"Standard Deviation:", None))
#if QT_CONFIG(tooltip)
        self.variable_input_11.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>If this option is checked the variable will have an initial value that is not dependend on a transition writing to it.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_11.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_6.setText(QCoreApplication.translate("Form", u"Use Initial Value:", None))
        self.use_initial_value_input.setText("")
#if QT_CONFIG(tooltip)
        self.variable_input_12.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>If this option is checked the inverse intervals are also included. For example, if the interval (&quot;&lt;&quot;, &quot;1.0&quot;) is entered the inverse interval is (&quot;&gt;=&quot;, &quot;1.0&quot;) is also included.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_12.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_7.setText(QCoreApplication.translate("Form", u"Include inverse intervals: ", None))
        self.inverse_intervals_input.setText("")
#if QT_CONFIG(tooltip)
        self.gen_initial_value.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>If this option is checked the initial value will be generated and and the  input for the initial value that is below this option will not be used.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.gen_initial_value.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_11.setText(QCoreApplication.translate("Form", u"Generate Initial Value:", None))
        self.gen_initial_value_input.setText("")
#if QT_CONFIG(tooltip)
        self.fixed_variable.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>If this option is checked the variable will have a fixed value once it has been written to once. Even if another transition writes to it, the value will not change.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.fixed_variable.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_12.setText(QCoreApplication.translate("Form", u"Fixed Variable:", None))
        self.fixed_variable_input.setText("")
#if QT_CONFIG(tooltip)
        self.trace_variable.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>If this option is checked the variable will be a trace variable, that is not part of any events.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.trace_variable.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_13.setText(QCoreApplication.translate("Form", u"Trace Variable:", None))
        self.trace_variable_input.setText("")
#if QT_CONFIG(tooltip)
        self.self_deviation.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This setting allows you to add some variance for the self reference feature. To understand how this feature works, consider the following example:</p><p align=\"center\">&quot;SELF_REFERENCE&quot; =&gt; &quot;'+'; '5' &quot;</p><p>If this setting is set to 0 the variable will be increased by 5 every time it is written to. If this setting is set to 2 the variable will be increased by a value in the range 3 to 7.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.self_deviation.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_15.setText(QCoreApplication.translate("Form", u"Self Reference maximum\n"
"Deviation:", None))
    # retranslateUi

