# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'VariableInputString.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QPlainTextEdit, QScrollArea, QSizePolicy,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(411, 391)
        self.vaiable_input_string = QScrollArea(Form)
        self.vaiable_input_string.setObjectName(u"vaiable_input_string")
        self.vaiable_input_string.setGeometry(QRect(0, 0, 411, 391))
        self.vaiable_input_string.setFrameShadow(QFrame.Sunken)
        self.vaiable_input_string.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.vaiable_input_string.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.vaiable_input_string.setWidgetResizable(True)
        self.scrollAreaWidgetContents_7 = QWidget()
        self.scrollAreaWidgetContents_7.setObjectName(u"scrollAreaWidgetContents_7")
        self.scrollAreaWidgetContents_7.setGeometry(QRect(0, 0, 409, 389))
        self.variable_input = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input.setObjectName(u"variable_input")
        self.variable_input.setGeometry(QRect(10, 120, 401, 27))
        self.initial_value_input = QLineEdit(self.variable_input)
        self.initial_value_input.setObjectName(u"initial_value_input")
        self.initial_value_input.setGeometry(QRect(110, 0, 281, 25))
        self.initial_value_input.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.initial_value_label = QLabel(self.variable_input)
        self.initial_value_label.setObjectName(u"initial_value_label")
        self.initial_value_label.setGeometry(QRect(0, 0, 91, 21))
        font = QFont()
        font.setPointSize(12)
        self.initial_value_label.setFont(font)
        self.initial_value_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.header_label = QLabel(self.scrollAreaWidgetContents_7)
        self.header_label.setObjectName(u"header_label")
        self.header_label.setGeometry(QRect(10, 5, 391, 21))
        self.header_label.setFont(font)
        self.header_label.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.line_17 = QFrame(self.scrollAreaWidgetContents_7)
        self.line_17.setObjectName(u"line_17")
        self.line_17.setGeometry(QRect(0, 30, 411, 3))
        self.line_17.setFrameShadow(QFrame.Plain)
        self.line_17.setFrameShape(QFrame.HLine)
        self.variable_input_2 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_2.setObjectName(u"variable_input_2")
        self.variable_input_2.setGeometry(QRect(10, 220, 401, 81))
        self.initial_value_label_2 = QLabel(self.variable_input_2)
        self.initial_value_label_2.setObjectName(u"initial_value_label_2")
        self.initial_value_label_2.setGeometry(QRect(0, 0, 51, 21))
        self.initial_value_label_2.setFont(font)
        self.initial_value_label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.values_input = QPlainTextEdit(self.variable_input_2)
        self.values_input.setObjectName(u"values_input")
        self.values_input.setGeometry(QRect(110, 5, 281, 71))
        self.values_input.setFont(font)
        self.variable_input_3 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_3.setObjectName(u"variable_input_3")
        self.variable_input_3.setGeometry(QRect(10, 300, 401, 81))
        self.dependencies_label = QLabel(self.variable_input_3)
        self.dependencies_label.setObjectName(u"dependencies_label")
        self.dependencies_label.setGeometry(QRect(0, 0, 111, 21))
        self.dependencies_label.setFont(font)
        self.dependencies_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.dependencies_input = QPlainTextEdit(self.variable_input_3)
        self.dependencies_input.setObjectName(u"dependencies_input")
        self.dependencies_input.setGeometry(QRect(110, 5, 281, 71))
        self.dependencies_input.setFont(font)
        self.variable_input_11 = QWidget(self.scrollAreaWidgetContents_7)
        self.variable_input_11.setObjectName(u"variable_input_11")
        self.variable_input_11.setGeometry(QRect(10, 50, 401, 27))
        self.initial_value_label_6 = QLabel(self.variable_input_11)
        self.initial_value_label_6.setObjectName(u"initial_value_label_6")
        self.initial_value_label_6.setGeometry(QRect(0, 0, 121, 21))
        self.initial_value_label_6.setFont(font)
        self.initial_value_label_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.use_initial_value_input = QCheckBox(self.variable_input_11)
        self.use_initial_value_input.setObjectName(u"use_initial_value_input")
        self.use_initial_value_input.setGeometry(QRect(140, 0, 82, 23))
        self.gen_initial_value = QWidget(self.scrollAreaWidgetContents_7)
        self.gen_initial_value.setObjectName(u"gen_initial_value")
        self.gen_initial_value.setGeometry(QRect(10, 80, 401, 27))
        self.initial_value_label_11 = QLabel(self.gen_initial_value)
        self.initial_value_label_11.setObjectName(u"initial_value_label_11")
        self.initial_value_label_11.setGeometry(QRect(0, 0, 161, 21))
        self.initial_value_label_11.setFont(font)
        self.initial_value_label_11.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.gen_initial_value_input = QCheckBox(self.gen_initial_value)
        self.gen_initial_value_input.setObjectName(u"gen_initial_value_input")
        self.gen_initial_value_input.setGeometry(QRect(160, 0, 82, 23))
        self.fixed_variable = QWidget(self.scrollAreaWidgetContents_7)
        self.fixed_variable.setObjectName(u"fixed_variable")
        self.fixed_variable.setGeometry(QRect(10, 160, 401, 27))
        self.initial_value_label_5 = QLabel(self.fixed_variable)
        self.initial_value_label_5.setObjectName(u"initial_value_label_5")
        self.initial_value_label_5.setGeometry(QRect(0, 0, 121, 21))
        self.initial_value_label_5.setFont(font)
        self.initial_value_label_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.fixed_variable_input = QCheckBox(self.fixed_variable)
        self.fixed_variable_input.setObjectName(u"fixed_variable_input")
        self.fixed_variable_input.setGeometry(QRect(140, 0, 82, 23))
        self.trace_variable = QWidget(self.scrollAreaWidgetContents_7)
        self.trace_variable.setObjectName(u"trace_variable")
        self.trace_variable.setGeometry(QRect(10, 190, 401, 27))
        self.initial_value_label_7 = QLabel(self.trace_variable)
        self.initial_value_label_7.setObjectName(u"initial_value_label_7")
        self.initial_value_label_7.setGeometry(QRect(0, 0, 131, 21))
        self.initial_value_label_7.setFont(font)
        self.initial_value_label_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.trace_variable_input = QCheckBox(self.trace_variable)
        self.trace_variable_input.setObjectName(u"trace_variable_input")
        self.trace_variable_input.setGeometry(QRect(140, 0, 82, 23))
        self.vaiable_input_string.setWidget(self.scrollAreaWidgetContents_7)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
#if QT_CONFIG(tooltip)
        self.variable_input.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>If the above option is checked this setting let's you adjust the initial value.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label.setText(QCoreApplication.translate("Form", u"Initial Value:", None))
#if QT_CONFIG(tooltip)
        self.header_label.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>The name and the type of the variable.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.header_label.setText(QCoreApplication.translate("Form", u"NAME (TYPE)", None))
#if QT_CONFIG(tooltip)
        self.variable_input_2.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This field allows to specify valid values for the variable. These values are used if a transition writes to the variable. The specification has to be done using the following syntax:</p><p align=\"center\">&quot;value1&quot;, &quot;value2&quot;, ...</p><p>Optionally weights can be specified for each value. Each weight has to be a whole positive number. If weights are specified they have to be specified using the following syntax:</p><p align=\"center\">&quot;value1&quot;, &quot;value2&quot; | value1_weight, value2_weight</p><p>If weights are specified the number of specified values must equal the number of specified weights.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_2.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_2.setText(QCoreApplication.translate("Form", u"Values:", None))
#if QT_CONFIG(tooltip)
        self.variable_input_3.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>This field allows to specify dependencies of the variable. These dependencies are considered when generating values for this variable. The specification has to be done using the following syntax:</p><p align=\"center\">&quot;logical_expression&quot; =&gt; &quot;constraint1&quot;, dependency2, ...</p><p>Example for the variable &quot;cancer_type&quot;: </p><p align=\"center\">&quot;gender == 'female' &quot; =&gt; &quot; '!=' ; 'prostate cancer' &quot;</p><p>The logical expression has to follow the same syntax as the guard transitions in a PNML model. The constraints have to follow the following syntax:</p><p align=\"center\">&quot; 'operator' ; 'value' &quot;</p><p>The operators that are alowed are: &quot;&lt;&quot;, &quot;&lt;=&quot;, &quot;&gt;&quot;, &quot;&gt;=&quot;, &quot;==&quot;, &quot;!=&quot;</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_3.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.dependencies_label.setText(QCoreApplication.translate("Form", u"Dependencies:", None))
#if QT_CONFIG(tooltip)
        self.variable_input_11.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>If this option is checked the variable will have an initial value that is not dependend on a transition writing to it.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.variable_input_11.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_6.setText(QCoreApplication.translate("Form", u"Use Initial Value:", None))
        self.use_initial_value_input.setText("")
#if QT_CONFIG(tooltip)
        self.gen_initial_value.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>If this option is checked the initial value will be generated and and the  input for the initial value that is below this option will not be used.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.gen_initial_value.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_11.setText(QCoreApplication.translate("Form", u"Generate Initial Value:", None))
        self.gen_initial_value_input.setText("")
#if QT_CONFIG(tooltip)
        self.fixed_variable.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>If this option is checked the variable will have a fixed value once it has been written to once. Even if another transition writes to it, the value will not change.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.fixed_variable.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_5.setText(QCoreApplication.translate("Form", u"Fixed Variable:", None))
        self.fixed_variable_input.setText("")
#if QT_CONFIG(tooltip)
        self.trace_variable.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>If this option is checked the variable will be a trace variable, that is not part of any events.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.trace_variable.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Dies ist ein Test</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.initial_value_label_7.setText(QCoreApplication.translate("Form", u"Trace Variable:", None))
        self.trace_variable_input.setText("")
    # retranslateUi

